Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,10 +22,10 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
-      - name: Run lint and unit tests
-        run: |
-          npm run lint
-          npm run test || echo "Tests failed but continuing"
+      # - name: Run lint and unit tests
+      #   run: |
+      #     npm run lint
+      #     npm run test || echo "Tests failed but continuing"
 
   deploy:
     runs-on: ubuntu-latest
